---
# AZURE KEY VAULT SECRET
# kubectl get AzureKeyVaultSecret -n alpha
# kubectl describe AzureKeyVaultSecret akvs-certificate-sync -n alpha
# kubectl get secret -n alpha
# kubectl describe secret razumovsky-certificate -n alpha
# kubectl get secret razumovsky-certificate -o yaml -n alpha
# kubectl logs deployment/akv2k8s-controller -n akv2k8s
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: akvs-certificate-sync
  namespace: alpha            # The namespace to create the secret in. Secrets must be in the same namespace as the resource!
spec:
  vault:
    name: kv-aks-d01  # Name of key vault.
    object:
      name: razumovsky-certificate  # Name of the certificate.
      type: certificate
  output:
    secret:
      name: razumovsky-certificate  # Kubernetes secret name.
      type: kubernetes.io/tls  # Kubernetes secret type.
---
